
package mynamespace.wsdl.authservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthPortType", targetNamespace = "http://mynamespace/wsdl/AuthService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AuthPortType {


    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "authorize")
    @WebResult(name = "authToken", partName = "authToken")
    public String authorize(
        @WebParam(name = "userName", partName = "userName")
        String userName,
        @WebParam(name = "password", partName = "password")
        String password);

}
